blank_issues_enabled: false
contact_links:
  - name: Ask questions or give feedback
    url: https://github.com/deven-org/boiler/discussions
    about: Start a discussion to ask questions or give feedback.
